FROM openjdk:11-slim
ENV SPRING_DATASOURCE_URL=${DATABASE_URL}
ENV SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
