# 개발 모드에서만 DevTools 활성화 (자동 리로드)
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

# CORS 설정
cors.allowed-origins=http://localhost:8787

# JPA 설정
spring.jpa.show-sql=true

# 파일 업로드 경로
file.upload-dir=uploads

# 세션 및 쿠키 설정
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.domain=localhost