spring.application.name=erpre

# ìë² í¬í¸ ì¤ì 
server.port=8787

# ë¼ì´ë¸ ë¦¬ë¡ë ì¤ì  (ì½ë ë³ê²½ ì ìëì¼ë¡ ìë¡ê³ ì¹¨)
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

## AWS EC2 PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATABASE_USERNAME}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# JPAì ë°ì´í°ë² ì´ì¤ ì¤í¤ë§ ìë ìë°ì´í¸ ì¤ì 
spring.jpa.hibernate.ddl-auto=none

# SQL ì¶ë ¥ ì ë³´ê¸° ì¢ê² ì ë ¬
spring.jpa.properties.hibernate.format_sql=true
# JPA ì¤í ì¤ SQL ì¿¼ë¦¬ ì¶ë ¥
spring.jpa.show-sql=true

# SQL ì¿¼ë¦¬ì ì£¼ìì ì¶ê°íì¬ ë¡ê·¸ì íì
spring.jpa.properties.hibernate.use_sql_comments=true
# SQL ì¿¼ë¦¬ ë¡ê·¸ë¥¼ DEBUG ë ë²¨ë¡ ì¤ì íì¬ ì¶ë ¥
logging.level.org.hibernate.SQL=DEBUG
# SQL ì¿¼ë¦¬ì ë°ì¸ë©ë íë¼ë¯¸í° ê°ì ë¡ê·¸ì ì¶ë ¥
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Hibernate ë°©ì¸ ì¤ì 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ê¸°ë³¸ íì¼ ì ì¥ ê²½ë¡
file.upload-dir=uploads

# ì¸ì ë° ì¿ í¤ ì¤ì 
server.servlet.session.timeout=24h
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.name=SESSION

# ì´ë©ì¼ SMTP ìë² ì¤ì 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hojinkim001155@gmail.com
spring.mail.password=ythq knql kvab hjlz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.debug=true
mail.imap.username=your_email_username
mail.imap.password=your_email_password

#
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}


