spring.application.name=erpre

# 서버 포트 설정
server.port=8787

# 라이브 리로드 설정
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

# AWS EC2 PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# JPA 설정
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 파일 업로드 경로
file.upload-dir=uploads

# 세션 및 쿠키 설정
server.servlet.session.timeout=24h
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.name=SESSION

# 이메일 SMTP 설정
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hojinkim001155@gmail.com
spring.mail.password=ythq knql kvab hjlz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.debug=true
mail.imap.username=your_email_username
mail.imap.password=your_email_password

# CORS 설정
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:8787}

# 쿠키 도메인 설정
server.servlet.session.cookie.domain=${COOKIE_DOMAIN:localhost}

# 정적 파일 서빙 경로 설정
spring.web.resources.static-locations=classpath:/static/,classpath:/public/,file:./src/main/resources/static/bundle/





