name: CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Node.js 20.17.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Node Dependencies
        run: npm install

      - name: Build React App (Webpack)
        run: npx webpack

      - name: Build Backend
        run: ./gradlew clean build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker Backend Build & Push
      - name: Docker Backend Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-springboot-app:latest